services:
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - YANDEX_TOKEN=TOKEN_HERE
      - APP_MODE=dev/production
    volumes:
      - ./src/database:/app/src/database
      - ./src/proxy_list.json:/app/src/proxy_list.json

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/hemolyzis.ru/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/hemolyzis.ru/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - backend
    restart: unless-stopped